# Adjusted from https://gitlab.com/gitlab-org/gitlab/-/blob/afe6d9af4b1096ee4aa1a6fa1a3709358ee22ec8/lib/gitlab/ci/templates/Gradle.gitlab-ci.yml

image: gradle:alpine

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - client/build
      - communication/build
      - game/build
      - gui/build
      - server/build
      - build
      - .gradle

test:
  stage: test
  script: gradle check --continue
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - client/build
      - communication/build
      - game/build
      - gui/build
      - server/build
      - build
      - .gradle
  artifacts:
    paths:
      - '**/build/reports/'

javadoc:
  stage: deploy
  script:
    - gradle javadoc
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - client/build
      - communication/build
      - game/build
      - gui/build
      - server/build
      - build
      - .gradle
  artifacts:
    paths:
      - '**/build/docs/javadoc/'
